# Generated by Django 4.2.28 on 2026-02-27 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'perfil__rol': 'CLIENTE'}, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='consultor',
            field=models.ForeignKey(blank=True, limit_choices_to={'perfil__rol': 'CONSULTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_consultor', to=settings.AUTH_USER_MODEL),
        ),
    ]
