# Generated by Django 4.2.28 on 2026-02-27 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico.'}, max_length=254, unique=True, verbose_name='correo electrónico')),
                ('is_staff', models.BooleanField(default=False, verbose_name='es staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('empresa', models.CharField(blank=True, max_length=255, verbose_name='empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='teléfono')),
                ('canal_preferido', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Correo electrónico')], default='EMAIL', max_length=20, verbose_name='¿cómo prefieres que nos comuniquemos?')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('tipo_servicio', models.CharField(choices=[('DESARROLLO', 'Desarrollo'), ('CONSULTORIA', 'Consultoría'), ('CAPACITACION', 'Capacitación'), ('OTROS', 'Otros')], default='DESARROLLO', max_length=20, verbose_name='tipo de servicio de interés')),
                ('enviado_email', models.BooleanField(default=False)),
                ('enviado_whatsapp', models.BooleanField(default=False)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('SOCIO', 'Socio'), ('CONSULTOR', 'Consultor'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=20, verbose_name='rol')),
                ('subtipo_cliente', models.CharField(blank=True, choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], max_length=20, null=True, verbose_name='subtipo de cliente')),
                ('razon_social', models.CharField(blank=True, max_length=255, verbose_name='razón social')),
                ('ruc', models.CharField(blank=True, max_length=20, verbose_name='RUC')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('especialidad', models.CharField(blank=True, max_length=255, verbose_name='especialidad')),
                ('tarifa_hora', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tarifa por hora')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfiles',
            },
        ),
    ]
