# Generated by Django 4.2.28 on 2026-02-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ATRASADO', 'Atrasado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('TRANSFERENCIA', 'Transferencia Bancaria'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta de Crédito/Débito'), ('YAPE', 'Yape'), ('PLIN', 'Plin')], max_length=20)),
                ('comprobante', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
